---
all:
  hosts:
    mac-mini-01:
      ansible_host: 127.0.0.1
      ansible_port: 22
      ansible_user: devops
  children:
    common_nodes:
      hosts:
        mac-mini-01:
    ios_builders:
      hosts:
        mac-mini-01:
    android_builders:
      hosts:
        mac-mini-01:
    llm_nodes:
      hosts:
        mac-mini-01:
    secure_nodes:
      hosts:
        mac-mini-01:
